#!/usr/bin/env bash

### bfym_channel ###
# - Shoutout to FolozaR1, you have suggested something that is now officially a script. You weren't entirely clear on what you wanted but I delivered regardless.

set -euo pipefail

printf "%b" "\nInput youtuber/channel: "
read -r -- channelSearch

if [[ -z "$channelSearch" ]]; then
  printf "Invalid input! Please try again."
  exit 1;
else
  printf "%b" "\nYou are searching for: $channelSearch"
  channelUrl=$(yt-dlp ytsearch1:"$channelSearch" --skip-download --print "%(channel_url)s")
  channelId=$(yt-dlp ytsearch1:"$channelSearch" --skip-download --print "%(uploader_id)s")
  printf "%b" "\nChannel located: $channelId"
  
  filterSel=${filterSel:-N}
  filter=${filter:-N}
  printf "%b" "\n1. Most viewed videos\n2. Highest comment count"  
  printf "%b" "\n\nChoose filter selector: "
  read -rn1 -- filterSel
  
  case $filterSel in
	  1)  filter=$(yt-dlp --dump-json --flat-playlist \ "$channelUrl" | jq -s 'sort_by(-.view_count) | .[:5] | .[] | .url')  ;;
	  #2)  filter=$(yt-dlp --dump-json --flat-playlist \ "$channelUrl" | jq -s 'sort_by(.like_count // 0) | .[] | "\(.like_count) - \(.title)"' | head -n 5 | cut -c 9- | sed 's/"//')  ;;
	  2)  filter=$(yt-dlp --dump-json --flat-playlist \ "$channelUrl" | jq -s 'sort_by(.comment_count) | .[:5] | .[] | .url')  ;;
	  *)
		  printf "%b" "\nInvalid input, please try again".
		  exit 1;
	  ;;
  esac
  
  printf "%b" "\nHere are $channelId's  videos:\n"
  
  arrayVideos=(${filter[@]})
  filter=${filter:-N}
  filter=$(printf "%s\n" "$filter" | tr -d '"')

  count=1
  for item in $filter; 
  do
	  watchList=$(printf "%u %s" "$count" "$item")
	  echo "$watchList"
	  ((count++))
	  title=$(yt-dlp --get-title "$item")
	  printf "%s\n" "$title"
	  
	  #comment out for speed
	  uploadDate=$(yt-dlp "$item" --skip-download --print "%(upload_date)s")
	  viewCount=$(yt-dlp "$item" --skip-download --print "%(view_count)s")
	  likeCount=$(yt-dlp "$item" --skip-download --print "%(like_count)s")
	  printf "%b" "Upload Date: $uploadDate\nView Count: $viewCount\nLike Count: $likeCount\n\n"
  done

  printf "%b" "\nSelect a video: "
  read -rn1 -- count

  case $count in
	1)  url=${arrayVideos[0]}  ;;
	2)  url=${arrayVideos[1]}  ;;
	3)  url=${arrayVideos[2]}  ;;
	4)  url=${arrayVideos[3]}  ;;
	5)  url=${arrayVideos[4]}  ;;
	6)  url=${arrayVideos[5]}  ;;
	*)  
		printf "Invalid input, please try again!"
	;;
  esac

  url=${url:-N}
  url="${url//\"/}"

  title=$(yt-dlp --get-title $url)

  printf "%b" "\nWould you like to save a copy of this video: $title? [y/N]: "
  read -rn1 -- dlConfirm
  dlConfirm=${dlConfirm:-N}

  case $dlConfirm in
	y|Y)
		printf "\nDownloading file\n"
		videoDl=$(yt-dlp "$url" | tail -n1)
		printf "%s" "$videoDl"
		result=$(yt-dlp --get-filename "$url")
		printf "%b" "\nYour video has been saved as: $result"
		printf "%b" "\nNow Streaming: $title\n"
		notify-send "bfym" "Now Steaming: $title"
		mpv "ytdl://$url"
		printf "Thank you for using bfym".
	;;
	n|N)
		printf "%b" "\nNow Streaming: $title\n"
		notify-send "bfym" "Now Streaming: $title"
		mpv "ytdl://$url"
		printf "Thank you for using bfym"
	;;
	*)
		printf "Invalid input! Please try again".
	;;
  esac
fi
